### ISSUE TITLE
Could not load native library zenginedict

### ISSUE THREAD

**Issue by SArsalanK** [NlptechProduct/Android-Keyboard#126]
2019-09-21 17:41:16.462 27768-27768/? E/JniUtils: Could not load native library zenginedict    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nlptech.zengine.sample-0qDvu3SQlmihC4RMa4bRJQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.nlptech.zengine.sample-0qDvu3SQlmihC4RMa4bRJQ==/lib/x86, /data/app/com.nlptech.zengine.sample-0qDvu3SQlmihC4RMa4bRJQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libzenginedict.so"        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)        at java.lang.System.loadLibrary(System.java:1669)        at com.nlptech.inputmethod.latin.utils.JniUtils.<clinit>(Unknown Source:3)        at com.nlptech.inputmethod.latin.utils.JniUtils.loadNativeLibrary(Unknown Source:0)        at com.android.inputmethod.latin.LatinIME.<clinit>(LatinIME.java:615)        at java.lang.Class.newInstance(Native Method)        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3514)        at android.app.ActivityThread.access$1300(ActivityThread.java:199)        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)        at android.os.Handler.dispatchMessage(Handler.java:106)        at android.os.Looper.loop(Looper.java:193)        at android.app.ActivityThread.main(ActivityThread.java:6669)        at java.lang.reflect.Method.invoke(Native Method)        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by NlptechProduct** [comment]
x86 and x86_64 platform have been supported.
